properties/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url, include
from django.views.generic.simple import direct_to_template
from views import *

urlpatterns = patterns('',

    url(r'^/$', direct_to_template, {'template': 'index.html'}, name='index'),

    #----- Departament ----#

    url(r'^departamento/venta/(?P<object_id>\d+)/([-\w]+)/$',
        departament_sale_detail, name='departament_sale_detail'
    ),
    url(r'^departamento/alquiler/(?P<object_id>\d+)/([-\w]+)/$',
        departament_rent_detail, name='departament_rent_detail'
    ),
    url(r'^departamentos/venta/$',
        departament_sale_list, name='departament_sale_list'
    ),
    url(r'^departamentos/alquiler/$',
        departament_rent_list, name='departament_rent_list'
    ),

    #-------- House -------#

    url(r'^casa/venta/(?P<object_id>\d+)/([-\w]+)/$',
        house_sale_detail, name='house_sale_detail'
    ),
    url(r'^casa/alquiler/(?P<object_id>\d+)/([-\w]+)/$',
        house_rent_detail, name='house_rent_detail'
    ),
    url(r'^casas/venta/$',
        house_sale_list, name='house_sale_list'
    ),
    url(r'^casas/alquiler/$',
        house_rent_list, name='house_rent_list'
    ),

    #------- Office -------#

    url(r'^oficina/venta/(?P<object_id>\d+)/([-\w]+)/$',
        office_sale_detail, name='office_sale_detail'
    ),
    url(r'^oficina/alquiler/(?P<object_id>\d+)/([-\w]+)/$',
        office_rent_detail, name='office_rent_detail'
    ),
    url(r'^oficinas/venta/$',
        office_sale_list, name='office_sale_list'
    ),
    url(r'^oficinas/alquiler/$',
        office_rent_list, name='office_rent_list'
    ),

    #--- Local Business ---#

    url(r'^local-comercial/venta/(?P<object_id>\d+)/([-\w]+)/$',
        localbusiness_sale_detail, name='localbusiness_sale_detail'
    ),
    url(r'^local-comercial/alquiler/(?P<object_id>\d+)/([-\w]+)/$',
        localbusiness_rent_detail, name='localbusiness_rent_detail'
    ),
    url(r'^locales-comerciales/venta/$',
        localbusiness_sale_list, name='localbusiness_sale_list'
    ),
    url(r'^locales-comerciales/alquiler/$',
        localbusiness_rent_list, name='localbusiness_rent_list'
    ),

    #-------- Shed --------#

    url(r'^galpon/venta/(?P<object_id>\d+)/([-\w]+)/$',
        shed_sale_detail, name='shed_sale_detail'
    ),
    url(r'^galpon/alquiler/(?P<object_id>\d+)/([-\w]+)/$',
        shed_rent_detail, name='shed_rent_detail'
    ),
    url(r'^galpones/venta/$',
        shed_sale_list, name='shed_sale_list'
    ),
    url(r'^galpones/alquiler/$',
        shed_rent_list, name='shed_rent_list'
    ),

    #-------- Land --------#

    url(r'^terreno/venta/(?P<object_id>\d+)/([-\w]+)/$',
        land_sale_detail, name='land_sale_detail'
    ),
    url(r'^terreno/alquiler/(?P<object_id>\d+)/([-\w]+)/$',
        land_rent_detail, name='land_rent_detail'
    ),
    url(r'^terrenos/venta/$',
        land_sale_list, name='land_sale_list'
    ),
    url(r'^terrenos/alquiler/$',
        land_rent_list, name='land_rent_list'
    ),
)

urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^test', include('myproject.properties.urls')),
    url(r'^test/administrador/', include(admin.site.urls)),
    url(r'^test/contacto/', include('myproject.contact.urls')),
    url(r'^', direct_to_template, {'template': 'fleepy.html'}),
)

properties/models.py
# -*- coding: utf-8 -*-

from choices import *
from django.db import models
from thumbs import ImageWithThumbsField
from myproject.realestate.models import RealEstate

class Service(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return u'%s' % self.name

class SaleManager(models.Manager):
    def get_query_set(self):
        return super(SaleManager, self).get_query_set().filter(operation='s')

class RentManager(models.Manager):
    def get_query_set(self):
        return super(RentManager, self).get_query_set().filter(operation='r')

class Property(models.Model):
    propietor = models.ForeignKey(RealEstate)
    operation = models.CharField(max_length=1, choices=OPERATIONS, verbose_name=u'Operación')
    price = models.PositiveIntegerField(verbose_name=u'Precio en Pesos')
    location = models.CharField(max_length=2, choices=LOCATIONS, verbose_name=u'Localidad')
    address = models.CharField(max_length=100, verbose_name=u'Dirección')
    orientation = models.CharField(max_length=1, choices=ORIENTATIONS, verbose_name=u'Orientación')
    services = models.ManyToManyField(Service, verbose_name=u'Servicios')
    description = models.TextField(verbose_name=u'Descripción')
    image0 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), verbose_name=u'Imagen 1')
    image1 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 2')
    image2 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 3')
    image3 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 4')
    image4 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 5')
    image5 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 6')
    image6 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 7')
    image7 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 8')
    image8 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 9')
    image9 = ImageWithThumbsField(upload_to='.', sizes=((45,33),(131,85),(485,300)), blank=True, verbose_name=u'Imagen 10')
    latitude = models.CharField(max_length='20')
    longitude = models.CharField(max_length='20')
    sale = SaleManager()
    rent = RentManager()

    def get_number_images(self):
        counter = 1
        if self.image1: counter += 1
        if self.image2: counter += 1
        if self.image3: counter += 1
        if self.image4: counter += 1
        if self.image5: counter += 1
        if self.image6: counter += 1
        if self.image7: counter += 1
        if self.image8: counter += 1
        if self.image9: counter += 1
        return counter

    class Meta:
        abstract = True
        ordering = ('-id',)

class Departament(Property):
    ambiences = models.PositiveIntegerField(default=0, verbose_name=u'Ambientes')
    rooms = models.PositiveIntegerField(default=0, verbose_name=u'Habitaciones')
    state = models.CharField(max_length=1, choices=STATES, verbose_name=u'Estado')
    baths = models.PositiveIntegerField(default=0, verbose_name=u'Baños')
    old = models.CharField(max_length=1, choices=OLDS, verbose_name=u'Antigüedad')
    surfaces = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Total')
    surfaces_coated = models.PositiveIntegerField(default=0, verbose_name=u'Superficie cubierta')
    garages = models.PositiveIntegerField(default=0, verbose_name=u'Garages')
    garages_coated = models.PositiveIntegerField(default=0, verbose_name=u'Garages Cubiertos')
    lifts = models.PositiveIntegerField(default=0, verbose_name=u'Ascensores')
    luminosity = models.CharField(max_length=1, choices=LUMINOSITY, verbose_name=u'Luminosidad')
    professional = models.BooleanField(verbose_name=u'Apto Profesional')
    commercial = models.BooleanField(verbose_name=u'Apto Comercial')
    expences = models.PositiveIntegerField(default=0, verbose_name=u'Expensas')

    class Meta:
        verbose_name = u'Departamento'
        verbose_name_plural = u'Departamentos'

class House(Property):
    ambiences = models.PositiveIntegerField(default=0, verbose_name=u'Ambientes')
    rooms = models.PositiveIntegerField(default=0, verbose_name=u'Habitaciones')
    state = models.CharField(max_length=1, choices=STATES, verbose_name=u'Estado')
    baths = models.PositiveIntegerField(default=1, verbose_name=u'Baños')
    old = models.CharField(max_length=1, choices=OLDS, verbose_name=u'Antigüedad')
    surfaces = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Total')
    surfaces_coated = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Cubierta')
    garages = models.PositiveIntegerField(default=0, verbose_name=u'Garages')
    garages_coated = models.PositiveIntegerField(default=0, verbose_name=u'Garages Cubiertos')
    floors = models.PositiveIntegerField(default=1, verbose_name=u'Plantas')
    luminosity = models.CharField(max_length=1, choices=LUMINOSITY, verbose_name=u'Luminosidad')
    professional = models.BooleanField(verbose_name=u'Apto profesional')
    commercial = models.BooleanField(verbose_name=u'Apto Comercial')

    class Meta:
        verbose_name = u'Casa'
        verbose_name_plural = u'Casas'

class Office(Property):
    ambiences = models.PositiveIntegerField(default=0, verbose_name=u'Ambientes')
    rooms = models.PositiveIntegerField(default=0, verbose_name=u'Habitaciones')
    expenses = models.PositiveIntegerField(default=0, verbose_name=u'Expensas en pesos')
    state = models.CharField(max_length=1, choices=STATES, verbose_name=u'Estado')
    baths = models.PositiveIntegerField(default=0, verbose_name=u'Baños')
    old = models.CharField(max_length=1, choices=OLDS, verbose_name=u'Antigüedad')
    surfaces = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Total')
    surfaces_coated = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Cubierta')
    garages = models.PositiveIntegerField(default=0, verbose_name=u'Garages')
    garages_coated = models.PositiveIntegerField(default=0, verbose_name=u'Garages Cubiertos')
    lifts = models.PositiveIntegerField(default=0, verbose_name=u'Ascensores')
    floor = models.PositiveIntegerField(default=1, verbose_name=u'Planta')
    luminosity = models.CharField(max_length=1, choices=LUMINOSITY, verbose_name=u'Luminosidad')
    professional = models.BooleanField(verbose_name=u'Apto Profesional')
    commercial = models.BooleanField(verbose_name=u'Apto Comercial')

    class Meta:
        verbose_name = u'Oficina'
        verbose_name_plural = u'Oficinas'

class LocalBusiness(Property):
    state = models.CharField(max_length=1, choices=STATES, verbose_name=u'Estado')
    baths = models.PositiveIntegerField(default=1, verbose_name=u'Baños')
    old = models.CharField(max_length=1, choices=OLDS, verbose_name=u'Antigüedad')
    surfaces = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Total')
    surfaces_coated = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Cubierta')
    garages = models.PositiveIntegerField(default=0, verbose_name=u'Garages')
    garages_coated = models.PositiveIntegerField(default=0, verbose_name=u'Garages Cubiertos')
    luminosity = models.CharField(max_length=1, choices=LUMINOSITY, verbose_name=u'Luminosidad')

    class Meta:
        verbose_name = u'Local Comercial'
        verbose_name_plural = u'Locales Comerciales'

class Shed(Property):
    state = models.CharField(max_length=1, choices=STATES, verbose_name=u'Estado')
    baths = models.PositiveIntegerField(default=1, verbose_name=u'Baños')
    old = models.CharField(max_length=1, choices=OLDS, verbose_name=u'Antigüedad')
    surfaces = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Total')
    surfaces_coated = models.PositiveIntegerField(default=0, verbose_name=u'Superficie Cubierta')
    garages = models.PositiveIntegerField(default=0, verbose_name=u'Garages')
    garages_coated = models.PositiveIntegerField(default=0, verbose_name=u'Garages Cubiertos')
    commercial = models.BooleanField(verbose_name=u'Apto Comercial')

    class Meta:
        verbose_name = u'Galpón'
        verbose_name_plural = u'Galpones'

class Land(Property):
    type_land = models.CharField(max_length=1, choices=TYPES_LAND, verbose_name=u'Tipo')
    pavement = models.CharField(max_length=10, verbose_name=u'Distancia a Pavimento')
    fencing = models.BooleanField(verbose_name=u'Cercado ?')
    livestock = models.BooleanField(verbose_name=u'Apto para Ganado ?')
    agriculture = models.BooleanField(verbose_name=u'Apto para Agricultura ?')
    pricipal_home = models.BooleanField(verbose_name=u'Posee Casa Principal ?')
    secundary_house = models.BooleanField(verbose_name=u'Posee Casa Secundaria ?')
    occupied = models.BooleanField(verbose_name=u'Ocupada')
    length_front = models.IntegerField(verbose_name=u'Longitud de Frente')
    length_back = models.IntegerField(verbose_name=u'Longitud de Fondo')
    total_surface = models.IntegerField(verbose_name=u'Superficie Total')
    contructed_surface = models.IntegerField(verbose_name=u'Superficie Construida')
    free_surface = models.IntegerField(verbose_name=u'Superfie Libre')
    form = models.CharField(max_length=1, choices=FORMS, verbose_name=u'Forma')
    topographic_level = models.CharField(max_length=1, choices=TOPOGRAFICS, verbose_name=u'Tipografía')

    class Meta:
        verbose_name = u'Terreno'
        verbose_name_plural = u'Terrenos'

templates/properties/departament_rent_list.html
{% extends "base.html" %}

{% block title %}Departamentos en Alquiler{% endblock %}

{% block centercolumn %}
<div class="centercolumn">
	<div id="maincontent">
		<div id="content">
			<h2 class="pagetitle">Departamentos <span class="colortext">en Alquiler</span></h2>
			<div id="breadcrumbs">
				<a href="{% url index %}">Inicio</a> &raquo; <strong>Departamentos en Alquiler</strong>
			</div>	
			{% for object in object_list %}
			<div class="list_properties">
				<div class="title_property2">
					<h2><a href="{% url departament_rent_detail object.id object.address|slugify %}">{{ object.address }} - {{ object.get_location_display }}</a></h2>
				</div>
				<div class="clear"></div>
				<div class="list_img">
					<img width="130" height="85" src="{{ object.image0.url }}" class="attachment-property-list wp-post-image" alt="" title="" />
				</div>
				<div class="list_text">
					<div class="avatar-right">
						<img alt='' src="{{ object.propietor.logo.url }}" class='avatar avatar-70 photo' height='70' width='70' />
					</div>
				<strong>$ {{ object.price }}</strong><br/>5 Beds | 4 Baths | 5,000 sq ft sqft | 0,19 Acres acres<br /><br /> Commercial<br/>Brokered By: Demo User<br />
				<span class="colortext">Open House: Mon 5/18, 2pm - 4pm</span>
				</div>
				<div class="clear"></div>
			</div>
			{% endfor %}
			<div class='wp-pagenavi'>
				<span class='pages'>Pagina 1 de 2</span>
				<span class='current'>1</span>
				<a href='http://demowp.templatesquare.com/lighthouse/properties/page/2/' class='page'>2</a>
				<a href="http://demowp.templatesquare.com/lighthouse/properties/page/2/" class="nextpostslink">&raquo;</a>
			</div>
		</div>
			
		<div class="sidebar_right">
			<div class="sidebar">
				<div class="widget-area">
					<ul>
						<li id="ts-property-search-3" class="widget-container widget_ts_property_search">
							<h2 class="widget-title">Buscar <span class="colortext">Propiedades</span></h2>
								<form id="search" name="searchform" method="get" action="http://demowp.templatesquare.com/lighthouse">
						<div id="searchMain">
                                                <div style="display:none;">
                        <input type="search" id="s" name="s" title="Search Property" placeholder="Search Property" value="search" />
                        </div>
                        <div class="advselectcont">
                            <label for="advlisttype">
                                Listing Type :<br />
                                <select name="advlisttype" id="advlisttype" class="advselect">
                                	<option value="">-Choose Type-</option>
									                                        <option value="For Sale"  />For Sale</option>
                                                                            <option value=" For Rent"  /> For Rent</option>
                                                                            <option value=" For Lease"  /> For Lease</option>
                                                                            <option value=" Auction"  /> Auction</option>
                                                                    </select>
                            </label>
                        </div>
                        <div class="advselectcont">
                            <label for="advproptype">
                                Property Type : <br />
                                <select name="advproptype" id="advproptype" class="advselect">
                                	<option value="">-Choose Type-</option>
									                                        <option value="Single Family"  />Single Family</option>
                                                                            <option value=" Multi Family"  /> Multi Family</option>
                                                                            <option value=" Condo or Townhome"  /> Condo or Townhome</option>
                                                                            <option value=" Commercial"  /> Commercial</option>
                                                                            <option value=" Lands and Lots"  /> Lands and Lots</option>
                                                                    </select>
                            </label>
                        </div>
                        <div class="clear"></div>
                        <label for="advcity">
                        	City : <br />
                        	<input type="text" id="advcity" name="advcity" class="txtlong" value="" />
                        </label>
                        <br />
                        <div id="advstatecont">
                        <label for="advstate">
                        	State : <br />
                        	<input type="text" id="advstate" name="advstate" value="" />
                        </label>
                        </div>
                        <div id="advzipcodecont">
                        <label for="advzipcode">
                        	Zip Code : <br />
                        	<input type="text" id="advzipcode" name="advzipcode" value="" />
                        </label>
                        </div>
                        <div class="clear"></div>
                        	Price : <br />
                        	<input type="text" id="advprice1" name="advprice1" class="txtadvprice" value="" />
                            to                            <input type="text" id="advprice2" name="advprice2" class="txtadvprice" value="" />
						<br />
                        <div id="advbedcont">
                        <label for="advbed">
                        	Bedroom(s) : <br />
                            <select name="advbed" id="advbed" class="advselect">
							                            	<option value="1" >1+</option>
                                                        	<option value="2" >2+</option>
                                                        	<option value="3" >3+</option>
                                                        	<option value="4" >4+</option>
                                                        	<option value="5" >5+</option>
                                                        </select>
                        </label>
                        </div>
                        <div id="advbathcont">
                        <label for="advbath">
                        	Bathroom(s) : <br />
                            <select name="advbath" id="advbath" class="advselect">
							                            	<option value="1"  >1+</option>
                                                        	<option value="2"  >2+</option>
                                                        	<option value="3"  >3+</option>
                                                        	<option value="4"  >4+</option>
                                                        	<option value="5"  >5+</option>
                                                        </select>
                        </label>
                        </div>
                        <div class="clear"></div>
                        <br />
                        <input type="hidden" name="post_type" value="property" />
						<button type="submit" value="search" id="searchsubmit">Search</button><br/>
						</div>
						</form>   
           </li></ul>        		

              <ul><li id="ts-property-tag-3" class="widget-container widget_ts_property_tag">			  	<h2 class="widget-title">Property Tag</h2><a href='http://demowp.templatesquare.com/lighthouse/propertytag/exotic/' class='tag-link-25' title='1 topic' style='font-size: 8pt;'>Exotic</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/for-sale/' class='tag-link-18' title='1 topic' style='font-size: 8pt;'>For Sale</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/highway/' class='tag-link-23' title='1 topic' style='font-size: 8pt;'>Highway</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/minimalist/' class='tag-link-6' title='4 topics' style='font-size: 22pt;'>Minimalist</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/pool-view/' class='tag-link-24' title='1 topic' style='font-size: 8pt;'>Pool View</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/private-spa/' class='tag-link-20' title='1 topic' style='font-size: 8pt;'>Private Spa</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/security/' class='tag-link-21' title='1 topic' style='font-size: 8pt;'>Security</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/single-family/' class='tag-link-22' title='1 topic' style='font-size: 8pt;'>Single Family</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/stucco/' class='tag-link-19' title='1 topic' style='font-size: 8pt;'>Stucco</a>
<a href='http://demowp.templatesquare.com/lighthouse/propertytag/villa/' class='tag-link-17' title='3 topics' style='font-size: 18.5pt;'>villa</a>           </li></ul>        <ul><li id="nav_menu-7" class="widget-container widget_nav_menu"><h2 class="widget-title">Information</h2><div class="menu-helpmenu-container"><ul id="menu-helpmenu" class="menu"><li id="menu-item-402" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-402"><a href="#">Help and FAQs</a></li>
<li id="menu-item-403" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-403"><a href="#">Home Price</a></li>
<li id="menu-item-404" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-404"><a href="#">Market View</a></li>
<li id="menu-item-590" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-590"><a href="#">Free Credit Report</a></li>
<li id="menu-item-591" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-591"><a href="#">Local Info</a></li>
<li id="menu-item-592" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-592"><a href="#">Buying 101</a></li>
<li id="menu-item-593" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-593"><a href="#">Closing and Beyond</a></li>
</ul></div></li></ul><ul><li id="text-8" class="widget-container widget_text"><h2 class="widget-title">Our Capabilities</h2>			<div class="textwidget"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at magna ornare justo pharetra congue sed et elit. Nunc lacinia ultricies iaculis.</p>
						<img src="http://demowp.templatesquare.com/demoimages/img-lighthouse/img2.jpg" alt="" class="alignnone" />
						<p>Aenean vulputate facilisis urna et adipiscing. In sollicitudin tellus sit amet dolor fringilla ullamcorper.</p>
						<ul>
							<li><a href="#">Resources</a></li>
							<li><a href="#">House Remodeling</a></li>
							<li><a href="#">Luxury Homes</a></li>
							<li><a href="#">Find a Contractor</a></li>
						</ul></div>
		</li></ul></div>
            </div><!-- end #sidebar -->
			</div><!-- end #sidebar_right -->
						
			<div class="clear"></div>
		</div><!-- end #maincontent -->
	</div>
{% endblock %}